# Práctica 1.1 — Probabilidad y Estadística 

## Análisis de la evolución poblacional mundial 

### Introducción 

En esta primera práctica se trabajará con datos reales de población obtenidos de Our World in Data (OWID), cuya fuente original es United Nations, World Population Prospects (2024). 

El propósito principal es familiarizarse con un conjunto de datos real y comprobar que el entorno de trabajo configurado para el curso funciona correctamente dentro de un Jupyter Notebook. 

Durante la práctica se utilizarán Python, Pandas y NumPy para cargar, explorar y analizar estadísticamente los datos. 

### Objetivo 

Utilizar un conjunto de datos real para comprobar el funcionamiento del entorno de análisis de datos y aplicar medidas estadísticas descriptivas básicas utilizando Pandas y NumPy. 

### Datos proporcionados 

Los datos se encuentran organizados en: 

data/ 
└── raw/ 
    ├── annual_population_growth/ 
    │   ├── annual-population-growth.csv 
    │   ├── annual-population-growth.metadata.json 
    │   └── annual-population-growth.README.md 
    │ 
    └── births_deaths/ 
        ├── births-and-deaths-projected-to-2100.csv 
        ├── births-and-deaths-projected-to-2100.metadata.json 
        └── births-and-deaths-projected-to-2100.README.md 

En esta práctica se utilizarán únicamente los datos históricos. 

Los archivos .metadata.json y .README.md deberán conservarse porque contienen información sobre la fuente, las variables y el procesamiento de los datos. 

### Notebook 

Todo el trabajo deberá realizarse en: 

notebooks/ 

└── 01_evolucion_poblacional.ipynb 

El notebook deberá seguir la misma estructura de actividades que esta práctica: 

## Práctica 1.1 — Probabilidad y Estadística 

Análisis de la evolución poblacional mundial 

### Objetivo 

### Actividad 1 — Identificación de la fuente 

### Actividad 2 — Carga y exploración de datos 

### Actividad 3 — Estadística descriptiva 

### Actividad 4 — Comprobación del entorno 

### Resultados 

Cada actividad deberá utilizar celdas Markdown para explicar brevemente lo realizado y celdas de código para ejecutar el análisis cuando corresponda.   

## Estructura del proyecto 

El proyecto deberá mantener la estructura: 

U1_1_probabilidad_estadistica/ 
│ 
├── .venv/ 
│ 
├── data/ 
│   └── raw/ 
│       ├── annual_population_growth/ 
│       └── births_deaths/ 
│ 
├── notebooks/ 
│   └── 01_evolucion_poblacional.ipynb 
│ 
├── src/ 
│ 
├── .gitignore 
├── README.md 
└── requirements.txt 

La carpeta .venv/ no deberá incluirse en el repositorio. 

### Entrega 

El estudiante deberá entregar su repositorio de GitHub con: 

- README.md; 
    

- requirements.txt; 
    

- .gitignore; 
    

- datos originales en data/raw/; 
    

- notebook 01_evolucion_poblacional.ipynb. 
    

El notebook deberá ejecutarse correctamente desde el inicio hasta el final. 

## Evidencia de aprendizaje 

La práctica permitirá comprobar que el estudiante puede: 

- trabajar con un conjunto de datos real; 
    

- identificar y citar su fuente; 
    

- utilizar un Jupyter Notebook; 
    

- importar Pandas y NumPy; 
    

- cargar un archivo CSV; 
    

- explorar un DataFrame; 
    

- calcular estadísticos descriptivos básicos; 
    

- comprobar las versiones de las herramientas utilizadas; 
    

- documentar su trabajo en un repositorio Git.


## Actividad 1 — Identificación de la fuente 

### Propósito 

Reconocer la procedencia del conjunto de datos antes de utilizarlo y documentar correctamente su fuente. 

### Instrucciones 

### Consulta los archivos: 

annual-population-growth.README.md 

annual-population-growth.metadata.json 

Utiliza la información proporcionada para identificar la fuente de los datos. 

En una celda Markdown del notebook documenta: 

Cita de la fuente 

Incluye en el notebook la referencia de la fuente utilizando la información de citación proporcionada por Our World in Data. 

Los datos utilizados en esta práctica provienen de **Our World in Data (OWID)**. 

La fuente original es **United Nations, World Population Prospects (2024)**. 

**Cita:** 

> UN, World Population Prospects (2024) – processed by Our World in Data. “Annual change in population – UN WPP” [dataset]. United Nations, “World Population Prospects”; United Nations, “World Population Prospects - Interim Update” [original data]. 

### Preguntas 

Responde brevemente: 

1. ¿Quién produjo originalmente los datos?    

2. ¿Qué organización los procesa para su utilización en Our World in Data? 

3. ¿Qué representa la variable que analizarás?

# Respuestas

1. ONU

2.  Our World In data

3.  El cambio poblacional con el paso de los años en cada país



UN, World Population Prospects (2024) – processed by Our World in Data

## Actividad 2 — Carga y exploración de datos 

### Propósito 

Comprobar que el entorno de Python, Pandas y Jupyter funciona correctamente y realizar una primera exploración del dataset. 

2.1 Importar las bibliotecas 

Importa: 

import pandas as pd 

import numpy as np 

2.2 Cargar el archivo CSV 

Utiliza pd.read_csv() para cargar: 

data/raw/annual_population_growth/annual-population-growth.csv 

2.3 Explorar el DataFrame 

Utiliza Pandas para obtener: 

- primeras filas; df.head() 
    

- dimensiones; df.shape 
    

- nombres de columnas; df.columns.tolist() 
    

- tipos de datos; df.dtypes 
    

- estadísticas descriptivas; df.describe() 
    

- cantidad de valores faltantes;  df.isnull().sum() 
    

- cantidad de entidades; df["Entity"].nunique()  
    

### Preguntas 

Responde brevemente: 

1. ¿Cuántas filas y columnas tiene el dataset? 
    

2. ¿Qué tipo de datos contiene la variable Year? 
    

3. ¿Existen valores faltantes? 
    

4. ¿Cuántas entidades diferentes contiene el dataset?

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('../data/raw/annual-population-growth/annual-population-growth.csv')

# Primeras Filas
df.head(5)

,Entity,Code,Year,Annual change in population,Annual population change (Projected)
0,Afghanistan,AFG,1951,103163.0,NaN
1,Afghanistan,AFG,1952,108441.0,NaN
2,Afghanistan,AFG,1953,108919.0,NaN
3,Afghanistan,AFG,1954,111251.0,NaN
4,Afghanistan,AFG,1955,119027.0,NaN

In [3]:
print("Número de Filas y Columnas:")
df.shape

Número de Filas y Columnas:

(38400, 5)

In [4]:
print("Nombres de Columnas")
df.columns.tolist()

Nombres de Columnas

['Entity',
 'Code',
 'Year',
 'Annual change in population',
 'Annual population change (Projected)']

In [5]:
print("Tipos de Datos de Cada Columna")
df.dtypes

Tipos de Datos de Cada Columna

Entity                                      str
Code                                        str
Year                                      int64
Annual change in population             float64
Annual population change (Projected)    float64
dtype: object

In [6]:

print("Resumen Estadístico:")
df.describe()

Resumen Estadístico:

,Year,Annual change in population,Annual population change (Projected)
count,38400.000000,1.868800e+04,1.971200e+04
mean,2025.500000,2.063019e+06,8.375481e+05
std,43.300872,9.440859e+06,5.816745e+06
min,1951.000000,-3.315935e+06,-2.291035e+07
25%,1988.000000,1.781000e+03,-9.742750e+03
50%,2025.500000,4.689800e+04,9.350000e+01
75%,2063.000000,3.021128e+05,1.411160e+05
max,2100.000000,9.337137e+07,7.206736e+07

In [7]:
print("Valores Nulos por Columna:")
df.isnull().sum()

Valores Nulos por Columna:

Entity                                      0
Code                                     1200
Year                                        0
Annual change in population             19712
Annual population change (Projected)    18688
dtype: int64

In [8]:

print("Número de Entidades Únicas:")
df["Entity"].nunique()

Número de Entidades Únicas:

256

### Preguntas 

Responde brevemente: 

1. ¿Cuántas filas y columnas tiene el dataset? 
    38400 filas y 5 columnas

2. ¿Qué tipo de datos contiene la variable Year? 
    int64

3. ¿Existen valores faltantes? 
    si, hay variass columnas con campos vacíos

4. ¿Cuántas entidades diferentes contiene el dataset? 
    256

## Actividad 3 — Estadística descriptiva 

### Propósito 

Aplicar medidas estadísticas básicas a una variable poblacional. 

### Instrucciones 

Selecciona un año del periodo histórico y filtra los datos correspondientes. 

Sobre la variable de cambio anual de población, calcula: 

- media; 
    

- mediana; 
    

- varianza; 
    

- desviación estándar; 
    

- mínimo; 
    

- máximo. 
    

Utiliza Pandas y NumPy cuando corresponda. 

Puedes utilizar operaciones como: 

df.mean() 

df.median() 

df.var() 

df.std() 

df.min() 

df.max() 

### Preguntas 

Responde brevemente: 

1. ¿Cuál es el valor de la media? 
    

2. ¿Cuál es el valor de la mediana? 
    

3. ¿Cuál es el valor de la desviación estándar? 
    

4. ¿Qué entidad presenta el valor mínimo y cuál el máximo?

In [9]:

print("Media:")
df['Annual change in population'].mean()

Media:

np.float64(2063019.2590967466)

In [10]:

print("Mediana:")
df['Annual change in population'].median()

Mediana:

np.float64(46898.0)

In [11]:

print("Varianza:")
df['Annual change in population'].var()

Varianza:

np.float64(89129827668962.33)

In [12]:

print("Desviación Estándar:")
df['Annual change in population'].std()

Desviación Estándar:

np.float64(9440859.477238411)

In [13]:

print("Mínimo:")
df['Annual change in population'].min()

Mínimo:

np.float64(-3315935.0)

In [14]:

print("Máximo:")
df['Annual change in population'].max()

Máximo:

np.float64(93371370.0)

### Preguntas 

Responde brevemente: 

1. ¿Cuál es el valor de la media? 
    2063019.2590967466

2. ¿Cuál es el valor de la mediana? 
    46898

3. ¿Cuál es el valor de la desviación estándar? 
    9440859.477238411

4. ¿Qué entidad presenta el valor mínimo y cuál el máximo? 
    min: -3315935 , max: 93371370

In [15]:
print("Elegir filtro por año")
df_2020 = df[df['Year'] == 2020]
df_2020.head(5)

Elegir filtro por año

,Entity,Code,Year,Annual change in population,Annual population change (Projected)
69,Afghanistan,AFG,2020,1212852.0,NaN
219,Africa (UN),UN_AFR,2020,32815675.0,NaN
369,Albania,ALB,2020,-13061.0,NaN
519,Algeria,DZA,2020,747543.0,NaN
669,American Samoa,ASM,2020,-451.0,NaN

In [16]:
print("Filtro para mostrar solo las columnas que quiero")
df_2020_ext_col1 = df_2020[['Entity', 'Year']]
df_2020_ext_col1.head(5)

Filtro para mostrar solo las columnas que quiero

             Entity  Year
69      Afghanistan  2020
219     Africa (UN)  2020
369         Albania  2020
519         Algeria  2020
669  American Samoa  2020

In [17]:
print("Filtrar datos utilizando filtros múltiples y condiciones")

print("Annual Change in Population between 1983 and 2021 in Mexico")


df_ext_MX_83_21 = df[(df['Entity'] == 'Mexico') & (df['Year'] >= 1983) & (df['Year'] <= 2021)]
df_ext_MX_83_21.head(5)

Filtrar datos utilizando filtros múltiples y condiciones
Annual Change in Population between 1983 and 2021 in Mexico

,Entity,Code,Year,Annual change in population,Annual population change (Projected)
22232,Mexico,MEX,1983,1537980.0,NaN
22233,Mexico,MEX,1984,1535610.0,NaN
22234,Mexico,MEX,1985,1536567.0,NaN
22235,Mexico,MEX,1986,1542223.0,NaN
22236,Mexico,MEX,1987,1551014.0,NaN

In [18]:
#df_min_population = df[df["Entity", "Annual change in population"] == df['Annual change in population'].min()]
df_max_population = df[df['Annual change in population'] == df['Annual change in population'].max()]

df_min_population = df[df['Annual change in population'] == df['Annual change in population'].min()]

df_min_country = df_min_population['Entity']
df_max_country = df_max_population['Entity']

print(df_min_country)
print(df_max_country)

35772    Ukraine
Name: Entity, dtype: str
37839    World
Name: Entity, dtype: str

## Actividad 4 — Comprobación del entorno 

### Propósito 

Comprobar que el notebook está utilizando correctamente las herramientas configuradas para la práctica. 

### Instrucciones 

En una celda del notebook muestra las versiones de: 

- Python; 
    

- Pandas; 
    

- NumPy. 
    

### Utiliza: 

import sys 

print("Python:", sys.version) 

print("Pandas:", pd.__version__) 

print("NumPy:", np.__version__) 

Verifica que las versiones corresponden al entorno virtual utilizado para la práctica. 

Finalmente, ejecuta nuevamente todas las celdas del notebook desde el inicio para comprobar que el análisis puede reproducirse correctamente. 

### Resultados 

El notebook deberá terminar mostrando: 

- información básica de la fuente; 
    

- la cita de la fuente; 
    

- el DataFrame cargado correctamente; 
    

- información sobre su estructura; 
    

- resultados de los estadísticos calculados; 
    

- versiones de Python, Pandas y NumPy. 
    

No es necesario realizar: 

- gráficas; 
    

- conclusiones; 
    

- análisis de proyecciones; 
    

- análisis temporal. 
    

Estos temas serán incorporados en prácticas posteriores.

In [19]:
import sys

print("Python" , sys.version)
print("Pandas" , pd.__version__)
print("Numpy" , np.__version__)

Python 3.14.7 (tags/v3.14.7:823f032, Aug  5 2026, 10:51:32) [MSC v.1944 64 bit (AMD64)]
Pandas 3.0.5
Numpy 2.5.2

In [20]:
df.loc[:, 'Entity']

0        Afghanistan
1        Afghanistan
2        Afghanistan
3        Afghanistan
4        Afghanistan
            ...
38395       Zimbabwe
38396       Zimbabwe
38397       Zimbabwe
38398       Zimbabwe
38399       Zimbabwe
Name: Entity, Length: 38400, dtype: str

In [21]:
df.iloc[600:610, 0:3]

             Entity Code  Year
600  American Samoa  ASM  1951
601  American Samoa  ASM  1952
602  American Samoa  ASM  1953
603  American Samoa  ASM  1954
604  American Samoa  ASM  1955
605  American Samoa  ASM  1956
606  American Samoa  ASM  1957
607  American Samoa  ASM  1958
608  American Samoa  ASM  1959
609  American Samoa  ASM  1960

In [22]:
df.loc[10000]

Entity                                  Equatorial Guinea
Code                                                  GNQ
Year                                                 2051
Annual change in population                           NaN
Annual population change (Projected)              46407.0
Name: 10000, dtype: object

In [23]:
df.loc[:,['Entity', 'Year', 'Annual change in population']]

            Entity  Year  Annual change in population
0      Afghanistan  1951                     103163.0
1      Afghanistan  1952                     108441.0
2      Afghanistan  1953                     108919.0
3      Afghanistan  1954                     111251.0
4      Afghanistan  1955                     119027.0
...            ...   ...                          ...
38395     Zimbabwe  2096                          NaN
38396     Zimbabwe  2097                          NaN
38397     Zimbabwe  2098                          NaN
38398     Zimbabwe  2099                          NaN
38399     Zimbabwe  2100                          NaN

[38400 rows x 3 columns]

In [24]:
## df.loc[:, ['Entity', 'Year']] 
df.loc[(df['Entity'] == 'Mexico') & (df['Year'] == 2020)]

,Entity,Code,Year,Annual change in population,Annual population change (Projected)
22269,Mexico,MEX,2020,1036075.0,NaN

In [25]:
df.iloc[0:5]

,Entity,Code,Year,Annual change in population,Annual population change (Projected)
0,Afghanistan,AFG,1951,103163.0,NaN
1,Afghanistan,AFG,1952,108441.0,NaN
2,Afghanistan,AFG,1953,108919.0,NaN
3,Afghanistan,AFG,1954,111251.0,NaN
4,Afghanistan,AFG,1955,119027.0,NaN

In [26]:
df.iloc[:,[0,2,3]]

            Entity  Year  Annual change in population
0      Afghanistan  1951                     103163.0
1      Afghanistan  1952                     108441.0
2      Afghanistan  1953                     108919.0
3      Afghanistan  1954                     111251.0
4      Afghanistan  1955                     119027.0
...            ...   ...                          ...
38395     Zimbabwe  2096                          NaN
38396     Zimbabwe  2097                          NaN
38397     Zimbabwe  2098                          NaN
38398     Zimbabwe  2099                          NaN
38399     Zimbabwe  2100                          NaN

[38400 rows x 3 columns]

In [27]:
df.iloc[0:4, 0:3]

        Entity Code  Year
0  Afghanistan  AFG  1951
1  Afghanistan  AFG  1952
2  Afghanistan  AFG  1953
3  Afghanistan  AFG  1954

In [28]:
df.set_index("Entity")

,Code,Year,Annual change in population,Annual population change (Projected)
Entity,,,,
Afghanistan,AFG,1951,103163.0,NaN
Afghanistan,AFG,1952,108441.0,NaN
Afghanistan,AFG,1953,108919.0,NaN
Afghanistan,AFG,1954,111251.0,NaN
Afghanistan,AFG,1955,119027.0,NaN
...,...,...,...,...
Zimbabwe,ZWE,2096,NaN,100752.0
Zimbabwe,ZWE,2097,NaN,91796.0
Zimbabwe,ZWE,2098,NaN,87605.0
Zimbabwe,ZWE,2099,NaN,76670.0
Zimbabwe,ZWE,2100,NaN,70019.0