In [1]:
import pandas as pd
import requests

# Fetch the data.
df = pd.read_csv("https://ourworldindata.org/grapher/life-expectancy.csv?v=1&csvType=full&useColumnShortNames=true", storage_options = {'User-Agent': 'Our World In Data data fetch/1.0'})

# Fetch the metadata
metadata = requests.get("https://ourworldindata.org/grapher/life-expectancy.metadata.json?v=1&csvType=full&useColumnShortNames=true").json()

In [2]:
df.head(10)

        entity code  year  life_expectancy_0
0  Afghanistan  AFG  1950            28.1563
1  Afghanistan  AFG  1951            28.5836
2  Afghanistan  AFG  1952            29.0138
3  Afghanistan  AFG  1953            29.4521
4  Afghanistan  AFG  1954            29.6975
5  Afghanistan  AFG  1955            30.3660
6  Afghanistan  AFG  1956            30.8303
7  Afghanistan  AFG  1957            31.3451
8  Afghanistan  AFG  1958            31.8400
9  Afghanistan  AFG  1959            32.3365

In [7]:
df.rename(columns={"entity":"country"}, inplace=True)

In [8]:
df.head(10)

       country code  year  life_expectancy_0
0  Afghanistan  AFG  1950            28.1563
1  Afghanistan  AFG  1951            28.5836
2  Afghanistan  AFG  1952            29.0138
3  Afghanistan  AFG  1953            29.4521
4  Afghanistan  AFG  1954            29.6975
5  Afghanistan  AFG  1955            30.3660
6  Afghanistan  AFG  1956            30.8303
7  Afghanistan  AFG  1957            31.3451
8  Afghanistan  AFG  1958            31.8400
9  Afghanistan  AFG  1959            32.3365

In [13]:
df.rename(columns={'country': 'país', 'year': 'año', 'code': 'código', 'life_expectancy_0': 'esperanza_de_vida'}, inplace=True)

In [14]:
df.head(10)

          país código   año  esperanza_de_vida
0  Afghanistan    AFG  1950            28.1563
1  Afghanistan    AFG  1951            28.5836
2  Afghanistan    AFG  1952            29.0138
3  Afghanistan    AFG  1953            29.4521
4  Afghanistan    AFG  1954            29.6975
5  Afghanistan    AFG  1955            30.3660
6  Afghanistan    AFG  1956            30.8303
7  Afghanistan    AFG  1957            31.3451
8  Afghanistan    AFG  1958            31.8400
9  Afghanistan    AFG  1959            32.3365

In [ ]:
df.set_index("país", inplace=True)

In [18]:
df.loc[df["país"] == "Mexico"]

         país código   año  esperanza_de_vida
12372  Mexico    MEX  1893            23.2900
12373  Mexico    MEX  1894            26.6200
12374  Mexico    MEX  1895            29.5200
12375  Mexico    MEX  1896            28.8000
12376  Mexico    MEX  1897            26.2400
...       ...    ...   ...                ...
12488  Mexico    MEX  2019            74.5302
12489  Mexico    MEX  2020            70.4492
12490  Mexico    MEX  2021            69.7499
12491  Mexico    MEX  2022            73.9731
12492  Mexico    MEX  2023            75.0690

[121 rows x 4 columns]

In [19]:
df.dropna(subset=["código"], inplace=True)
df.isnull().sum()

país                 0
código               0
año                  0
esperanza_de_vida    0
dtype: int64

In [23]:
resultado = (
    df[df["año"] == 2020].groupby("país") ["esperanza_de_vida"].mean().sort_values(ascending=True)
)
resultado

país
Central African Republic    50.5959
Nigeria                     53.0724
Chad                        53.0818
Lesotho                     55.1325
Somalia                     57.0948
                             ...
Saint Barthelemy            84.0707
Macao                       84.6100
Japan                       84.6703
Hong Kong                   84.7073
Monaco                      86.0893
Name: esperanza_de_vida, Length: 246, dtype: float64